branch-defaults:
  tutorial:
    environment: NodeJSDockerEB-app-dev
    group_suffix: null
global:
  application_name: NodeJSDockerEB-app
  default_ec2_keyname: null
  default_platform: Docker 1.11.2
  default_region: eu-west-1
  profile: eb-cli
  sc: git
